### ISSUE TITLE
Multiple comment blocks

### ISSUE THREAD

**Issue by stephenway** [jonathantneal/mdcss#14]
Being able to comment throughout a given partial file would be nice. Currently when you have multiple comments in a file it treats it as a completely separate set of documentation. 

Is there a way that `mdcss` could account for extra comment blocks formatted the same way in the same file?

**Comment by maoberlehner** [comment]
+1

It would be really nice to "extend" an existing mdcss block like:

``` css
/*---
title: Section XY
name: section_xy
---

Lorem Ipsum
*/
.some-class { ... }

.more-classes { ... }

/*---
extends: section_xy
---

Dolor sit
*/
```

The result should be something like:

``` html
<section>
<h2 id="section_xy">Section XY</h2>
<p>Lorem Ipsum</p>
<p>Dolor sit</p>
</section>
```

@stephenway if I misinterpreted your proposal and what you mean is different from what I wrote above, please let me now and I open a separate issue.
