### ISSUE TITLE
Modifier search and populate

### ISSUE THREAD

**Issue by stephenway** [jonathantneal/mdcss#15]
It would be great if there were a way to have the styleguide be aware that there are multiple modifier classes and to list out each one separately using a `${modifiers}` variable, or something similar. Kind of like modeling what a component should be, and then reusing that documentation for every other variation.

``` css
/*---
'''example
<button class="${modifiers}">Button</button>
'''
*/
```

**Comment by tomByrer** [comment]
Would be very handy for colors & typography:

``` scss
/*---
'''example
<div style="font-size:25px;background:{$modifiers};" class="styleguide-color">{$modifiers}</div>
'''
*/
$color-blue-bright1: #00518a;
$color-blue-bright2: #005ea0;
$color-blue-dark: #052338;
$color-gray-darkcool: #454c54;
$color-gray-darkwarm: #333;
```
