### ISSUE TITLE
scss support / variable documentation

### ISSUE THREAD

**Issue by maoberlehner** [jonathantneal/mdcss#21]
one of my last (s)css documentation problems, that is not already solved by this tool, is how to document scss variable(s) (values).

currently I'm doing something like this:

`````` css
$variable1: 'value1';
$variable2: 'value2';
$variable3: 'value3';
/*---
title: Variables

---

```css
$variable1: '#{$variable1}';
$variable2: '#{$variable2}';
$variable3: '#{$variable3}';
-```
*/
``````

The output is somewhat ok but the problem is - this is really ugly, not very "DRY" and it is impossible to document the values of scss maps that way.

The "perfect" solution would be to use the scss files as source for mdcss (instead of the compiled css) and to implement a special comment format like:

``` css
/*---
title: Variables

---

@var $variable1
@var $variable2
@var $variable3
*/
$variable1: 'value1';
$variable2: 'value2';
$variable3: 'value3';
```

The output should be something like:

``` html
<section>
  <h2>Variables</h2>
  <div class="variables">
    <span class="variable-name">$variable1</span>: <span class="variable-value">'value1'</span>;<br />
    <span class="variable-name">$variable2</span>: <span class="variable-value">'value2'</span>;<br />
    <span class="variable-name">$variable3</span>: <span class="variable-value">'value3'</span>;
  </div>
</section>
```
