### ISSUE TITLE
[html_example] does not render as text

### ISSUE THREAD

**Issue by maboiteaspam** [jonathantneal/mdcss#3]
Hi,

Given a css file like,

`````` css

/*---
title:   f-cap
section: Text

---

Capitalize text:

​```html_example

<div class='f-cap'>lorem ipsum</div>
<span class='f-cap'>LOREM IPSUM</span>
​```
*/

.f-cap{
    text-transform: capitalize;
}
``````

In the resulting output the html_example MD block is not recognized and printed as HTML.

Looks like,

``````
Text

f-cap

Capitalize text:

​```html_example

lorem ipsum
LOREM IPSUM ​```
``````

`````` html
<section id="f-cap">
                <h3 class="doc-section-heading">f-cap</h3>

                <div>
                    <p>Capitalize text:</p>
<p>​```html_example</p>
<p></p><div class="f-cap">lorem ipsum</div>
<span class="f-cap">LOREM IPSUM</span>
​```<p></p>


                </div>
            </section>
``````

not sure where is the issue.
