### ISSUE TITLE
Styleguide doesn't port over css

### ISSUE THREAD

**Issue by Risto-Stevcev** [jonathantneal/mdcss#42]
I just followed the basic example

```css
/* index.css */

/*---
title:   Buttons
section: Base CSS
---

Button styles can be applied to any element. Typically you'll want to use
either a `<button>` or an `<a>` element:

\```example:html
<button class="btn">Click</button>
<a class="btn" href="/some-page">Some Page</a>
\```
*/

.btn {
	background-color: black;
	color: white;
}
```
And tried it with postcss:
```js
// postcss.config.js
const postcssPresetEnv = require('postcss-preset-env')

module.exports = {
  plugins: [
    postcssPresetEnv({ browsers: '> 3%, ie 11' }),
    require('mdcss')({}),
  ]
}
```
```
cat css/index.css | yarn postcss > output.css
```

It generated the styleguide but it doesn't port over the styles from `index.css`
