### ISSUE TITLE
How can I read own CSS file?

### ISSUE THREAD

**Issue by msaktype** [jonathantneal/mdcss#9]
I tried to use mdcss in gulp, but I have a problem.

gulpfile.js:

``` js
var postcss = require('gulp-postcss');
var gulp = require('gulp')

gulp.task('css', function () {
    return gulp.src('./src/css/*.css')
      .pipe(
        postcss([
            require('mdcss')
        ])
      );
});
```

src/css/sample.css(the code is picked from README):

`````` css
/*---
title:   Buttons
section: Base CSS

---

Button styles can be applied to any element. Typically you'll want to use
either a `<button>` or an `<a>` element:

​```example:html
<button class="btn">Click</button>
<a class="btn" href="/some-page">Some Page</a>
​```
*/

.btn {
    background-color: black;
    color: white;
}
``````

Above is the code I tried.

But, I could not get a correct result.  Here is the generated code block.

`````` html
<main>

        <section id="base-css">
            <h2>Base CSS</h2>
            <div>


        <section id="buttons">
            <h3>Buttons</h3>
            <div>
                <p>Button styles can be applied to any element. Typically you&#39;ll want to use
either a <code>&lt;button&gt;</code> or an <code>&lt;a&gt;</code> element:</p>
<p>​```example:html</p>
<p><button class="btn">Click</button>
<a class="btn" href="/some-page">Some Page</a>
​```</p>


            </div>
        </section>

            </div>
        </section>

    <footer>Last modified Wednesday, 13 January 2016 16:09
</main>
``````

There are no styles in `sample.css`(`.btn{}` rule).

I wish your help.
